#!/usr/bin/env node
import { readFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { execSync } from "node:child_process";
import { parseArgs } from "node:util";
import { TASKS_DIR, agentWorktreeLabel } from "./paths.mjs";
import { tmpdir } from "node:os";

const { values } = parseArgs({
  options: {
    "task-id": { type: "string" },
    action: { type: "string" },
    file: { type: "string" },
  },
});

const taskId = values["task-id"];
const action = values.action;

if (!taskId) {
  console.error(JSON.stringify({ error: "--task-id is required" }));
  process.exit(1);
}

const taskPath = join(TASKS_DIR, `${taskId}.json`);
const task = JSON.parse(readFileSync(taskPath, "utf-8"));

const repoName = task.repoPath.split("/").pop();
const worktreePath =
  task.worktreePath ||
  join(
    process.env.HOME,
    ".cursor",
    "worktrees",
    repoName,
    agentWorktreeLabel(task.branch)
  );

const baseBranch = task.baseBranch || "main";

function getMergeBase() {
  try {
    return execSync(
      `git -C "${worktreePath}" merge-base ${baseBranch} HEAD`,
      { encoding: "utf-8" }
    ).trim();
  } catch {
    return baseBranch;
  }
}

const mergeBase = getMergeBase();

const AUTO_GENERATED_PATTERNS = [
  /^package-lock\.json$/,
  /^yarn\.lock$/,
  /^pnpm-lock\.yaml$/,
  /^Gemfile\.lock$/,
  /^Pipfile\.lock$/,
  /^poetry\.lock$/,
  /^composer\.lock$/,
  /^go\.sum$/,
  /^Cargo\.lock$/,
];

function isAutoGenerated(file) {
  const basename = file.split("/").pop();
  return AUTO_GENERATED_PATTERNS.some((p) => p.test(basename));
}

function getChangedFiles() {
  try {
    const files = execSync(
      `git -C "${worktreePath}" diff --name-only ${mergeBase}..HEAD`,
      { encoding: "utf-8" }
    );
    return files
      .trim()
      .split("\n")
      .filter(Boolean)
      .filter((f) => !isAutoGenerated(f));
  } catch {
    return [];
  }
}

function getDiffStat(file) {
  try {
    const numstat = execSync(
      `git -C "${worktreePath}" diff --numstat ${mergeBase}..HEAD -- "${file}"`,
      { encoding: "utf-8" }
    ).trim();

    if (!numstat) return { additions: 0, deletions: 0, isNew: false };

    const [added, deleted] = numstat.split("\t");
    const additions = added === "-" ? 0 : Number(added);
    const deletions = deleted === "-" ? 0 : Number(deleted);

    let isNew = false;
    try {
      execSync(
        `git -C "${worktreePath}" cat-file -e ${mergeBase}:"${file}" 2>/dev/null`,
        { encoding: "utf-8" }
      );
    } catch {
      isNew = true;
    }

    return { additions, deletions, isNew };
  } catch {
    return { additions: 0, deletions: 0, isNew: false };
  }
}

if (action === "open") {
  try {
    execSync(`cursor --add "${worktreePath}"`, { stdio: "inherit" });
    console.log(JSON.stringify({ taskId, worktreePath, action: "opened" }));
  } catch (err) {
    console.error(JSON.stringify({ error: err.message }));
    process.exit(1);
  }
} else if (action === "close") {
  try {
    execSync(`cursor --remove "${worktreePath}"`, { stdio: "inherit" });
    console.log(JSON.stringify({ taskId, worktreePath, action: "closed" }));
  } catch (err) {
    console.error(JSON.stringify({ error: err.message }));
    process.exit(1);
  }
} else if (action === "diff") {
  const file = values.file;
  if (!file) {
    console.error(JSON.stringify({ error: "--file is required for diff action" }));
    process.exit(1);
  }

  const tmpBase = join(tmpdir(), `cursor-power-review-${taskId}`);
  mkdirSync(tmpBase, { recursive: true });

  try {
    const basePath = join(tmpBase, file.replace(/\//g, "__"));
    execSync(
      `git -C "${worktreePath}" show ${mergeBase}:${file} > "${basePath}" 2>/dev/null`,
      { encoding: "utf-8" }
    );
    const currentPath = join(worktreePath, file);
    execSync(`cursor --diff "${basePath}" "${currentPath}"`, { stdio: "inherit" });
    console.log(JSON.stringify({ taskId, mergeBase, file, action: "diff opened" }));
  } catch {
    const currentPath = join(worktreePath, file);
    execSync(`cursor "${currentPath}"`, { stdio: "inherit" });
    console.log(JSON.stringify({ taskId, file, action: "new file opened" }));
  }
} else {
  const files = getChangedFiles();
  const changedFiles = files.map((file) => ({
    path: file,
    diffStat: getDiffStat(file),
  }));
  const info = {
    taskId,
    worktreePath,
    prUrl: task.prUrl,
    branch: task.branch,
    baseBranch,
    prompt: task.prompt,
    riskScore: task.riskScore || null,
    changedFiles,
  };
  console.log(JSON.stringify(info, null, 2));
}
